export type ProductShape = {
  _id: string;
  slug?: string;
  title: string;
  description: string;
  summary?: string;
  productInfo?: string;
  productType?: string;
  umbraReady?: boolean;
  deliveryMode?: "direct" | "ipfs_encrypted";
  ipfsCid?: string;
  encryptedContentKey?: string;
  encryptionAlgorithm?: string;
  fileName?: string;
  mimeType?: string;
  status?: "draft" | "published";
  price?: number;
  priceSol: number;
  priceUsdc?: number;
  priceUsdt?: number;
  priceAudd?: number;
  currency?: "PUSD" | "SOL" | "USDC" | "USDT" | "AUDD";
  contentUrl: string;
  coverUrl?: string;
  thumbnailUrl?: string;
  creatorWallet: string;
  payoutWallet?: string;
  salesCount: number;
  createdAt?: string;
};
