export type ProductShape = {
  _id: string;
  slug?: string;
  title: string;
  description: string;
  summary?: string;
  productInfo?: string;
  productType?: string;
  deliveryMode?: "direct" | "ipfs_encrypted";
  ipfsCid?: string;
  encryptedContentKey?: string;
  encryptionAlgorithm?: string;
  fileName?: string;
  mimeType?: string;
  deliveryFiles?: {
    ipfsCid?: string;
    contentUrl?: string;
    fileName?: string;
    mimeType?: string;
  }[];
  status?: "draft" | "published";
  price?: number;
  priceSol: number;
  priceUsdc?: number;
  currency?: "PUSD" | "SOL" | "USDC";
  contentUrl: string;
  coverUrl?: string;
  thumbnailUrl?: string;
  creatorWallet: string;
  payoutWallet?: string;
  salesCount: number;
  createdAt?: string;
};
